*** Starting uWSGI 2.0.18 (32bit) on [Fri May 22 20:12:47 2020] ***
compiled with version: 8.3.0 on 16 July 2019 12:06:45
os: Linux-4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/pi/rasp-pi-flask
detected binary path: /home/pi/rasp-pi-flask/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 29184
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/pi/rasp-pi-flask/app_uwsgi.sock fd 3
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /home/pi/rasp-pi-flask
Set PythonHome to /home/pi/rasp-pi-flask
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xafc858
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64400 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
added /home/pi/rasp-pi-flask/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xafc858 pid: 8305 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 8305, cores: 1)
*** Starting uWSGI 2.0.18 (32bit) on [Fri May 22 20:15:20 2020] ***
compiled with version: 8.3.0 on 16 July 2019 12:06:45
os: Linux-4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/pi/rasp-pi-flask
detected binary path: /home/pi/rasp-pi-flask/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 29184
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/pi/rasp-pi-flask/app_uwsgi.sock fd 3
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /home/pi/rasp-pi-flask
Set PythonHome to /home/pi/rasp-pi-flask
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1adc858
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64400 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
added /home/pi/rasp-pi-flask/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1adc858 pid: 8357 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 8357, cores: 1)
[pid: 8357|app: 0|req: 1/1] 192.168.254.41 () {42 vars in 643 bytes} [Fri May 22 20:15:26 2020] GET / => generated 12 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (32bit) on [Fri May 22 20:30:46 2020] ***
compiled with version: 8.3.0 on 16 July 2019 12:06:45
os: Linux-4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /home/pi/rasp-pi-flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 29184
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/pi/rasp-pi-flask/app_uwsgi.sock fd 4
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /home/pi/rasp-pi-flask
Set PythonHome to /home/pi/rasp-pi-flask
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1357e18
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64400 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
added /home/pi/rasp-pi-flask/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1357e18 pid: 8796 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 8796, cores: 1)
[pid: 8796|app: 0|req: 1/1] 192.168.254.41 () {44 vars in 674 bytes} [Fri May 22 20:31:13 2020] GET / => generated 12 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
Fri May 22 20:31:13 2020 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /favicon.ico (ip 192.168.254.41) !!!
Fri May 22 20:31:13 2020 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /favicon.ico (192.168.254.41)
OSError: write error
[pid: 8796|app: 0|req: 2/2] 192.168.254.41 () {42 vars in 601 bytes} [Fri May 22 20:31:13 2020] GET /favicon.ico => generated 0 bytes in 2 msecs (HTTP/1.1 404) 2 headers in 0 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.18 (32bit) on [Fri May 22 20:35:12 2020] ***
compiled with version: 8.3.0 on 16 July 2019 12:06:45
os: Linux-4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /home/pi/rasp-pi-flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 29184
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/pi/rasp-pi-flask/app_uwsgi.sock fd 4
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /home/pi/rasp-pi-flask
Set PythonHome to /home/pi/rasp-pi-flask
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x19efe18
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64400 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
added /home/pi/rasp-pi-flask/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x19efe18 pid: 346 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 346, cores: 1)
[pid: 346|app: 0|req: 1/1] 192.168.254.41 () {44 vars in 674 bytes} [Fri May 22 20:35:25 2020] GET / => generated 12 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 346|app: 0|req: 2/2] 192.168.254.41 () {44 vars in 674 bytes} [Fri May 22 20:54:15 2020] GET / => generated 12 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
Fri May 22 20:54:15 2020 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /favicon.ico (ip 192.168.254.41) !!!
Fri May 22 20:54:15 2020 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /favicon.ico (192.168.254.41)
OSError: write error
[pid: 346|app: 0|req: 3/3] 192.168.254.41 () {42 vars in 601 bytes} [Fri May 22 20:54:15 2020] GET /favicon.ico => generated 0 bytes in 3 msecs (HTTP/1.1 404) 2 headers in 0 bytes (0 switches on core 0)
[pid: 346|app: 0|req: 4/4] 192.168.254.41 () {42 vars in 643 bytes} [Sat May 23 14:42:41 2020] GET / => generated 12 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
Sat May 23 14:42:41 2020 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /favicon.ico (ip 192.168.254.41) !!!
Sat May 23 14:42:41 2020 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /favicon.ico (192.168.254.41)
OSError: write error
[pid: 346|app: 0|req: 5/5] 192.168.254.41 () {40 vars in 570 bytes} [Sat May 23 14:42:41 2020] GET /favicon.ico => generated 0 bytes in 2 msecs (HTTP/1.1 404) 2 headers in 0 bytes (0 switches on core 0)
[pid: 346|app: 0|req: 6/6] 192.168.254.41 () {42 vars in 651 bytes} [Sat May 23 14:47:39 2020] GET /blog => generated 232 bytes in 2 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (32bit) on [Sat May 23 14:47:51 2020] ***
compiled with version: 8.3.0 on 16 July 2019 12:06:45
os: Linux-4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /home/pi/rasp-pi-flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 29184
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/pi/rasp-pi-flask/app_uwsgi.sock fd 4
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /home/pi/rasp-pi-flask
Set PythonHome to /home/pi/rasp-pi-flask
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1104e18
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64400 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
added /home/pi/rasp-pi-flask/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1104e18 pid: 327 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 327, cores: 1)
[pid: 327|app: 0|req: 1/1] 192.168.254.41 () {44 vars in 682 bytes} [Sat May 23 14:49:24 2020] GET /blog => generated 10 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 327|app: 0|req: 2/2] 192.168.254.41 () {42 vars in 643 bytes} [Sat May 23 15:57:13 2020] GET / => generated 12 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
Sat May 23 15:57:13 2020 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /favicon.ico (ip 192.168.254.41) !!!
Sat May 23 15:57:13 2020 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /favicon.ico (192.168.254.41)
OSError: write error
[pid: 327|app: 0|req: 3/3] 192.168.254.41 () {40 vars in 570 bytes} [Sat May 23 15:57:13 2020] GET /favicon.ico => generated 0 bytes in 2 msecs (HTTP/1.1 404) 2 headers in 0 bytes (0 switches on core 0)
[pid: 327|app: 0|req: 4/4] 192.168.254.41 () {42 vars in 651 bytes} [Sat May 23 15:57:24 2020] GET /blog => generated 10 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
Sat May 23 15:57:25 2020 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /favicon.ico (ip 192.168.254.41) !!!
Sat May 23 15:57:25 2020 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /favicon.ico (192.168.254.41)
OSError: write error
[pid: 327|app: 0|req: 5/5] 192.168.254.41 () {40 vars in 570 bytes} [Sat May 23 15:57:25 2020] GET /favicon.ico => generated 0 bytes in 2 msecs (HTTP/1.1 404) 2 headers in 0 bytes (0 switches on core 0)
[pid: 327|app: 0|req: 6/6] 192.168.254.41 () {42 vars in 643 bytes} [Sat May 23 16:33:28 2020] GET / => generated 12 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 327|app: 0|req: 7/7] 192.168.254.41 () {40 vars in 570 bytes} [Sat May 23 16:33:28 2020] GET /favicon.ico => generated 232 bytes in 2 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
[pid: 327|app: 0|req: 8/8] 192.168.254.41 () {42 vars in 643 bytes} [Sun May 24 03:47:52 2020] GET / => generated 12 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (32bit) on [Sun May 24 04:07:07 2020] ***
compiled with version: 8.3.0 on 16 July 2019 12:06:45
os: Linux-4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /home/pi/rasp-pi-flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 29184
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/pi/rasp-pi-flask/app_uwsgi.sock fd 4
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /home/pi/rasp-pi-flask
Set PythonHome to /home/pi/rasp-pi-flask
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1815e18
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64400 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
added /home/pi/rasp-pi-flask/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1815e18 pid: 341 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 341, cores: 1)
Traceback (most recent call last):
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/rasp-pi-flask/app_pkg/routes.py", line 9, in index
    return render_template('hello.html', message="Hello World!")
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: hello.html
[pid: 341|app: 0|req: 1/1] 192.168.254.41 () {42 vars in 643 bytes} [Sun May 24 04:09:07 2020] GET / => generated 0 bytes in 71 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.18 (32bit) on [Sun May 24 04:13:07 2020] ***
compiled with version: 8.3.0 on 16 July 2019 12:06:45
os: Linux-4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/pi/rasp-pi-flask
detected binary path: /home/pi/rasp-pi-flask/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 29184
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/pi/rasp-pi-flask/app_uwsgi.sock fd 3
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /home/pi/rasp-pi-flask
Set PythonHome to /home/pi/rasp-pi-flask
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xe8c768
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64400 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
added /home/pi/rasp-pi-flask/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xe8c768 pid: 784 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 784, cores: 1)
Traceback (most recent call last):
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/rasp-pi-flask/app_pkg/routes.py", line 9, in index
    return render_template('hello.html', message="Hello World!")
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: hello.html
[pid: 784|app: 0|req: 1/1] 192.168.254.41 () {44 vars in 674 bytes} [Sun May 24 04:13:15 2020] GET / => generated 0 bytes in 62 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/rasp-pi-flask/app_pkg/routes.py", line 9, in index
    return render_template('hello.html', message="Hello World!")
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: hello.html
[pid: 784|app: 0|req: 2/2] 192.168.254.41 () {44 vars in 674 bytes} [Sun May 24 04:13:16 2020] GET / => generated 0 bytes in 57 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/rasp-pi-flask/app_pkg/routes.py", line 9, in index
    return render_template('hello.html', message="Hello World!")
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: hello.html
[pid: 784|app: 0|req: 3/3] 192.168.254.41 () {44 vars in 674 bytes} [Sun May 24 04:13:17 2020] GET / => generated 0 bytes in 61 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 2038, in shutdown
    h.flush()
  File "/usr/lib/python3.7/logging/__init__.py", line 1017, in flush
    if self.stream and hasattr(self.stream, "flush"):
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/werkzeug/local.py", line 328, in __bool__
    return bool(self._get_current_object())
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/pi/rasp-pi-flask/lib/python3.7/site-packages/flask/logging.py", line 30, in wsgi_errors_stream
    return request.environ["wsgi.errors"] if request else sys.stderr
KeyError: 'wsgi.errors'
*** Starting uWSGI 2.0.18 (32bit) on [Sun May 24 00:55:23 2020] ***
compiled with version: 8.3.0 on 16 July 2019 12:06:45
os: Linux-4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /home/pi/rasp-pi-flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 29184
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/pi/rasp-pi-flask/app_uwsgi.sock fd 4
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /home/pi/rasp-pi-flask
Set PythonHome to /home/pi/rasp-pi-flask
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x853df0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64400 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
added /home/pi/rasp-pi-flask/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x853df0 pid: 369 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 369, cores: 1)
*** Starting uWSGI 2.0.18 (32bit) on [Sun May 24 01:03:49 2020] ***
compiled with version: 8.3.0 on 16 July 2019 12:06:45
os: Linux-4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020
nodename: raspberrypi
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /home/pi/rasp-pi-flask/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 29184
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/pi/rasp-pi-flask/app_uwsgi.sock fd 4
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /home/pi/rasp-pi-flask
Set PythonHome to /home/pi/rasp-pi-flask
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1e3edf0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64400 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
added /home/pi/rasp-pi-flask/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1e3edf0 pid: 803 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 803, cores: 1)
[pid: 803|app: 0|req: 1/1] 192.168.254.41 () {42 vars in 643 bytes} [Sun May 24 01:04:12 2020] GET / => generated 72 bytes in 23 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
Sun May 24 01:04:12 2020 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /favicon.ico (ip 192.168.254.41) !!!
Sun May 24 01:04:12 2020 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /favicon.ico (192.168.254.41)
OSError: write error
[pid: 803|app: 0|req: 2/2] 192.168.254.41 () {40 vars in 570 bytes} [Sun May 24 01:04:12 2020] GET /favicon.ico => generated 0 bytes in 2 msecs (HTTP/1.1 404) 2 headers in 0 bytes (0 switches on core 0)
[pid: 803|app: 0|req: 3/3] 192.168.254.41 () {42 vars in 643 bytes} [Sun May 24 01:07:46 2020] GET / => generated 72 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 803|app: 0|req: 4/4] 192.168.254.41 () {44 vars in 674 bytes} [Sun May 24 01:10:42 2020] GET / => generated 72 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 803|app: 0|req: 5/5] 192.168.254.41 () {44 vars in 674 bytes} [Sun May 24 01:10:44 2020] GET / => generated 72 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 803|app: 0|req: 6/6] 192.168.254.41 () {42 vars in 653 bytes} [Sun May 24 01:10:49 2020] GET /index => generated 72 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 803|app: 0|req: 7/7] 192.168.254.254 () {42 vars in 647 bytes} [Sun May 24 01:24:04 2020] GET / => generated 72 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 803|app: 0|req: 8/8] 192.168.254.254 () {40 vars in 574 bytes} [Sun May 24 01:24:04 2020] GET /favicon.ico => generated 232 bytes in 2 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
